{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b3daecaf-12fa-4919-8d71-babfb495572e",
   "metadata": {
    "jupyter": {
     "source_hidden": true
    }
   },
   "outputs": [],
   "source": [
    "from surprise import Dataset, Reader, SVD\n",
    "from surprise.model_selection import train_test_split\n",
    "from surprise import accuracy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "438d560a-d9e2-4e7a-a9a7-5245524ef11a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# import streamlit as st\n",
    "import pandas as pd\n",
    "import zipfile\n",
    "\n",
    "# Extract the CSV file from the zip archive\n",
    "with zipfile.ZipFile('clean_dataset.zip', 'r') as zipf:\n",
    "    zipf.extractall()\n",
    "\n",
    "# Load the clean DataFrame\n",
    "df_clean = pd.read_csv('clean_dataset.csv')\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "2e572d3a-db1e-4a1e-a2a9-e3ba34e895ce",
   "metadata": {},
   "outputs": [],
   "source": [
    "df = df_clean"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "845af720-a039-4610-af0c-b664dfc6f08d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>fit</th>\n",
       "      <th>user_id</th>\n",
       "      <th>bust_size</th>\n",
       "      <th>item_id</th>\n",
       "      <th>weight</th>\n",
       "      <th>rating</th>\n",
       "      <th>rented_for</th>\n",
       "      <th>review_text</th>\n",
       "      <th>body_type</th>\n",
       "      <th>review_summary</th>\n",
       "      <th>category</th>\n",
       "      <th>height</th>\n",
       "      <th>size</th>\n",
       "      <th>age</th>\n",
       "      <th>review_date</th>\n",
       "      <th>processed_review</th>\n",
       "      <th>processed_summary</th>\n",
       "      <th>sentiment_score</th>\n",
       "      <th>hybrid_rating</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>fit</td>\n",
       "      <td>420272</td>\n",
       "      <td>34d</td>\n",
       "      <td>2260466</td>\n",
       "      <td>137.0</td>\n",
       "      <td>5</td>\n",
       "      <td>vacation</td>\n",
       "      <td>An adorable romper! Belt and zipper were a lit...</td>\n",
       "      <td>hourglass</td>\n",
       "      <td>So many compliments!</td>\n",
       "      <td>romper</td>\n",
       "      <td>172.72</td>\n",
       "      <td>14</td>\n",
       "      <td>28.0</td>\n",
       "      <td>April 20, 2016</td>\n",
       "      <td>['ador', 'romper', 'belt', 'zipper', 'littl', ...</td>\n",
       "      <td>['mani', 'compliment']</td>\n",
       "      <td>0.625000</td>\n",
       "      <td>5.625000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>fit</td>\n",
       "      <td>273551</td>\n",
       "      <td>34b</td>\n",
       "      <td>153475</td>\n",
       "      <td>132.0</td>\n",
       "      <td>5</td>\n",
       "      <td>other</td>\n",
       "      <td>I rented this dress for a photo shoot. The the...</td>\n",
       "      <td>straight &amp; narrow</td>\n",
       "      <td>I felt so glamourous!!!</td>\n",
       "      <td>gown</td>\n",
       "      <td>167.64</td>\n",
       "      <td>12</td>\n",
       "      <td>36.0</td>\n",
       "      <td>June 18, 2013</td>\n",
       "      <td>['rent', 'dress', 'photo', 'shoot', 'theme', '...</td>\n",
       "      <td>['felt', 'glamour']</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>5.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>fit</td>\n",
       "      <td>909926</td>\n",
       "      <td>34c</td>\n",
       "      <td>126335</td>\n",
       "      <td>135.0</td>\n",
       "      <td>4</td>\n",
       "      <td>formal affair</td>\n",
       "      <td>I rented this for my company's black tie award...</td>\n",
       "      <td>pear</td>\n",
       "      <td>Dress arrived on time and in perfect condition.</td>\n",
       "      <td>dress</td>\n",
       "      <td>165.10</td>\n",
       "      <td>8</td>\n",
       "      <td>34.0</td>\n",
       "      <td>February 12, 2014</td>\n",
       "      <td>['rent', 'compani', 'black', 'tie', 'award', '...</td>\n",
       "      <td>['dress', 'arriv', 'time', 'perfect', 'condit']</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>5.000000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>fit</td>\n",
       "      <td>151944</td>\n",
       "      <td>34b</td>\n",
       "      <td>616682</td>\n",
       "      <td>145.0</td>\n",
       "      <td>5</td>\n",
       "      <td>wedding</td>\n",
       "      <td>I have always been petite in my upper body and...</td>\n",
       "      <td>athletic</td>\n",
       "      <td>Was in love with this dress !!!</td>\n",
       "      <td>gown</td>\n",
       "      <td>175.26</td>\n",
       "      <td>12</td>\n",
       "      <td>27.0</td>\n",
       "      <td>September 26, 2016</td>\n",
       "      <td>['alway', 'petit', 'upper', 'bodi', 'extrem', ...</td>\n",
       "      <td>['love', 'dress']</td>\n",
       "      <td>0.976562</td>\n",
       "      <td>5.976562</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>fit</td>\n",
       "      <td>734848</td>\n",
       "      <td>32b</td>\n",
       "      <td>364092</td>\n",
       "      <td>138.0</td>\n",
       "      <td>4</td>\n",
       "      <td>date</td>\n",
       "      <td>Didn't actually wear it. It fit perfectly. The...</td>\n",
       "      <td>athletic</td>\n",
       "      <td>Traditional with a touch a sass</td>\n",
       "      <td>dress</td>\n",
       "      <td>172.72</td>\n",
       "      <td>8</td>\n",
       "      <td>45.0</td>\n",
       "      <td>April 30, 2016</td>\n",
       "      <td>['actual', 'wear', 'fit', 'perfectli', 'fabric...</td>\n",
       "      <td>['tradit', 'touch', 'sass']</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>4.000000</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   fit  user_id bust_size  item_id  weight  rating     rented_for  \\\n",
       "0  fit   420272       34d  2260466   137.0       5       vacation   \n",
       "1  fit   273551       34b   153475   132.0       5          other   \n",
       "2  fit   909926       34c   126335   135.0       4  formal affair   \n",
       "3  fit   151944       34b   616682   145.0       5        wedding   \n",
       "4  fit   734848       32b   364092   138.0       4           date   \n",
       "\n",
       "                                         review_text          body_type  \\\n",
       "0  An adorable romper! Belt and zipper were a lit...          hourglass   \n",
       "1  I rented this dress for a photo shoot. The the...  straight & narrow   \n",
       "2  I rented this for my company's black tie award...               pear   \n",
       "3  I have always been petite in my upper body and...           athletic   \n",
       "4  Didn't actually wear it. It fit perfectly. The...           athletic   \n",
       "\n",
       "                                     review_summary category  height  size  \\\n",
       "0                              So many compliments!   romper  172.72    14   \n",
       "1                           I felt so glamourous!!!     gown  167.64    12   \n",
       "2  Dress arrived on time and in perfect condition.     dress  165.10     8   \n",
       "3                   Was in love with this dress !!!     gown  175.26    12   \n",
       "4                   Traditional with a touch a sass    dress  172.72     8   \n",
       "\n",
       "    age         review_date  \\\n",
       "0  28.0      April 20, 2016   \n",
       "1  36.0       June 18, 2013   \n",
       "2  34.0   February 12, 2014   \n",
       "3  27.0  September 26, 2016   \n",
       "4  45.0      April 30, 2016   \n",
       "\n",
       "                                    processed_review  \\\n",
       "0  ['ador', 'romper', 'belt', 'zipper', 'littl', ...   \n",
       "1  ['rent', 'dress', 'photo', 'shoot', 'theme', '...   \n",
       "2  ['rent', 'compani', 'black', 'tie', 'award', '...   \n",
       "3  ['alway', 'petit', 'upper', 'bodi', 'extrem', ...   \n",
       "4  ['actual', 'wear', 'fit', 'perfectli', 'fabric...   \n",
       "\n",
       "                                 processed_summary  sentiment_score  \\\n",
       "0                           ['mani', 'compliment']         0.625000   \n",
       "1                              ['felt', 'glamour']         0.000000   \n",
       "2  ['dress', 'arriv', 'time', 'perfect', 'condit']         1.000000   \n",
       "3                                ['love', 'dress']         0.976562   \n",
       "4                      ['tradit', 'touch', 'sass']         0.000000   \n",
       "\n",
       "   hybrid_rating  \n",
       "0       5.625000  \n",
       "1       5.000000  \n",
       "2       5.000000  \n",
       "3       5.976562  \n",
       "4       4.000000  "
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_clean.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1839872f-b160-45c3-b9ed-9783121bb298",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "from surprise import SVD, Dataset, Reader\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.decomposition import TruncatedSVD\n",
    "from sklearn.metrics.pairwise import cosine_similarity\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "cf3a9c98-0656-4dee-b767-a7a436dfad51",
   "metadata": {},
   "outputs": [],
   "source": [
    "# import streamlit as st\n",
    "# from surprise import SVD, Dataset, Reader\n",
    "# from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "# from sklearn.decomposition import TruncatedSVD\n",
    "# from sklearn.metrics.pairwise import cosine_similarity\n",
    "# import pandas as pd\n",
    "# import numpy as np\n",
    "# import joblib\n",
    "\n",
    "# # Load SVD model\n",
    "# final_svd_model = SVD(n_epochs=10, lr_all=0.01, reg_all=0.4)\n",
    "\n",
    "# # Load content-based model\n",
    "# def train_content_based_model(df):\n",
    "#     sample_size = 20000\n",
    "#     df_sample = df.sample(n=sample_size, random_state=42)\n",
    "\n",
    "#     # Combine relevant text features into a single column for content-based filtering\n",
    "#     df_sample['content'] = df_sample['review_summary'].fillna('') + ' ' + df_sample['category'].fillna('') + ' ' \\\n",
    "#                            + df_sample['body_type'].fillna('') + ' ' + df_sample['rented_for'].fillna('')\n",
    "\n",
    "#     # Create a TF-IDF vectorizer\n",
    "#     tfidf_vectorizer = TfidfVectorizer(stop_words='english')\n",
    "\n",
    "#     # Fit and transform the content column\n",
    "#     tfidf_matrix = tfidf_vectorizer.fit_transform(df_sample['content'])\n",
    "\n",
    "#     # Implement batch processing for cosine similarity\n",
    "#     def calculate_cosine_similarity_in_batches(matrix, batch_size=1000):\n",
    "#         num_items = matrix.shape[0]\n",
    "#         cosine_sim_batches = []\n",
    "\n",
    "#         for i in range(0, num_items, batch_size):\n",
    "#             start_idx = i\n",
    "#             end_idx = min((i + batch_size), num_items)\n",
    "#             batch_matrix = matrix[start_idx:end_idx, :]\n",
    "#             cosine_sim_batch = cosine_similarity(batch_matrix, matrix, dense_output=False)\n",
    "#             cosine_sim_batches.append(cosine_sim_batch)\n",
    "\n",
    "#         return np.vstack(cosine_sim_batches)\n",
    "\n",
    "#     # Calculate cosine similarity in batches\n",
    "#     cosine_sim = calculate_cosine_similarity_in_batches(tfidf_matrix)\n",
    "\n",
    "#     # Apply dimensionality reduction using TruncatedSVD\n",
    "#     num_components = 100\n",
    "#     svd = TruncatedSVD(n_components=num_components)\n",
    "#     tfidf_matrix_reduced = svd.fit_transform(tfidf_matrix)\n",
    "#     cosine_sim_reduced = cosine_similarity(tfidf_matrix_reduced, dense_output=False)\n",
    "\n",
    "#     # Save the content-based model\n",
    "#     joblib.dump((cosine_sim_reduced, df_sample['item_id']), 'content_based_model.pkl')\n",
    "\n",
    "#     return cosine_sim_reduced, df_sample['item_id']\n",
    "\n",
    "# # Streamlit App\n",
    "# st.title(\"Fashion Recommender System\")\n",
    "\n",
    "# # Sidebar with input options\n",
    "# st.sidebar.header(\"User Input Features\")\n",
    "\n",
    "# # Add input options based on your model features (e.g., body type, rented for, etc.)\n",
    "# user_input = {}\n",
    "# user_input['Body Type'] = st.sidebar.selectbox('Select Body Type', df_clean['body_type'].unique())\n",
    "# user_input['Rented For'] = st.sidebar.selectbox('Select Rented For', df_clean['rented_for'].unique())\n",
    "# # Add more input options as needed...\n",
    "\n",
    "# # Add a button to trigger recommendations\n",
    "# if st.sidebar.button('Get Recommendations'):\n",
    "#     # Load content-based model\n",
    "#     content_based_model, item_ids = train_content_based_model(df_clean)\n",
    "\n",
    "#     # Function to get content-based recommendations for a given item after dimensionality reduction\n",
    "#     def get_content_based_recommendations_reduced(item_id, cosine_sim=content_based_model, df=df_clean, item_ids=item_ids):\n",
    "#         idx = item_ids[item_ids == item_id].index[0]\n",
    "#         sim_scores = list(enumerate(cosine_sim[idx]))\n",
    "#         sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)\n",
    "#         sim_scores = sim_scores[1:11]  # Exclude the item itself and take top 10\n",
    "#         item_indices = [score[0] for score in sim_scores]\n",
    "#         return df['item_id'].iloc[item_indices]\n",
    "\n",
    "#     # Example: Get content-based recommendations for an item\n",
    "#     item_id_to_recommend_for = 1973037\n",
    "#     content_based_recommendations_reduced = get_content_based_recommendations_reduced(item_id_to_recommend_for)\n",
    "\n",
    "#     # Display the recommendations\n",
    "#     st.write(f\"Content-Based Recommendations (Reduced) for Item {item_id_to_recommend_for}:\")\n",
    "#     st.write(content_based_recommendations_reduced)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "292a8228-c87e-4c6c-97af-408aac89ebb0",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pickle"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "f8b7b662-7381-49a2-be4c-803b3f857fb4",
   "metadata": {},
   "outputs": [],
   "source": [
    "pickle_in = open('als_model',\"rb\")\n",
    "als_model = pickle.load(pickle_in)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "8f875bd7-c09e-4e32-934e-bf0c1227af09",
   "metadata": {},
   "outputs": [],
   "source": [
    "def main():\n",
    "    st.title(\"Fashion Recommender System\")\n",
    "\n",
    "    # Add input elements (e.g., sliders, dropdowns) for user features\n",
    "    # Example: category, body_type, rented_for\n",
    "    category = st.selectbox(\"Select category:\", df['category'].unique())\n",
    "    body_type = st.selectbox(\"Select body type:\", df['body_type'].unique())\n",
    "    rented_for = st.selectbox(\"Select rented for:\", df['rented_for'].unique())\n",
    "\n",
    "    # Add a button to trigger recommendations\n",
    "    if st.button(\"Get Recommendations\"):\n",
    "        # Call the recommendation function and display the results\n",
    "        recommendations = get_recommendations(category, body_type, rented_for)\n",
    "        st.write(\"Recommendations:\")\n",
    "        st.write(recommendations)\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "6a1ed75d-8c44-4384-8cb5-807bc644e263",
   "metadata": {},
   "outputs": [],
   "source": [
    "def get_recommendations(category, body_type, rented_for):\n",
    "    # Filter the dataset based on user inputs\n",
    "    filtered_data = df[(df['category'] == category) & (df['body_type'] == body_type) & (df['rented_for'] == rented_for)]\n",
    "\n",
    "    if filtered_data.empty:\n",
    "        return \"No recommendations available for the selected criteria.\"\n",
    "\n",
    "    # Get user-specific recommendations from collaborative filtering\n",
    "    user_id_to_predict = 420272  # Replace with an actual user ID\n",
    "    item_ids_to_predict = filtered_data['item_id'].unique()\n",
    "\n",
    "    predictions_collab = [als_model.predict(user_id_to_predict, item_id) for item_id in item_ids_to_predict]\n",
    "    predicted_ratings_collab = [(prediction.iid, prediction.est) for prediction in predictions_collab]\n",
    "\n",
    "    # Sort collaborative filtering predictions by rating in descending order\n",
    "    sorted_predictions_collab = sorted(predicted_ratings_collab, key=lambda x: x[1], reverse=True)\n",
    "\n",
    "    # Get content-based recommendations for a sample item (replace with user-specific item)\n",
    "    sample_item_id = filtered_data['item_id'].iloc[0]\n",
    "    content_based_recommendations = get_content_based_recommendations_reduced(sample_item_id)\n",
    "\n",
    "    # Combine collaborative filtering and content-based recommendations\n",
    "    combined_recommendations = sorted_predictions_collab + content_based_recommendations.tolist()\n",
    "\n",
    "    # Deduplicate and sort the combined recommendations\n",
    "    unique_recommendations = list(set(combined_recommendations))\n",
    "    sorted_recommendations = sorted(unique_recommendations, key=lambda x: x[1], reverse=True)\n",
    "\n",
    "    # Return the top N recommendations\n",
    "    top_n = 10\n",
    "    return sorted_recommendations[:top_n]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "df494129-ce91-4c71-9080-f9ba09932759",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4ed3038f-049b-43a1-97f8-60fd2d932e24",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
